### ISSUE TITLE
crossprod error

### ISSUE THREAD

**Issue by bdelepine** [MetaSys-LISBP/PhysioFit#1]
Hello @pierremillard,

I've been trying to play with PhysioFit and I got an unexpected traceback with the following code:

```r
source("./PhysioFit-master/physio_fit.R", chdir=TRUE)

res = physio_fit(datfile="example.txt")
```

(I use a copy of PhysioFit extracted from the archive on the master branch. The example file is a copy of the file shipped in the example folder.)

console + traceback:
```r
Initialize the system...
Estimate fluxes...
it=0	res=2.600188e+14
it=1	res=260033830	normstep=1.414212	btk=1
it=2	res=95666376	normstep=0.05244889	btk=1
it=3	res=35196044	normstep=0.05289034	btk=1
it=4	res=12948900	normstep=0.05288783	btk=1
it=5	res=4764008	normstep=0.05244526	btk=1
it=6	res=1752665	normstep=0.05235102	btk=1
it=7	res=644720.1	normstep=0.05211036	btk=1
it=8	res=237067.3	normstep=0.05147469	btk=1
it=9	res=87071.05	normstep=0.04980738	btk=1
it=10	res=31877.28	normstep=0.04568199	btk=1

 Error in crossprod(res, ap) : non-conformable arguments 
3.
crossprod(res, ap) at nlsic.R#262
2.
nlsic(sys$params[sys$to_est], Cost, u = sys$u, co = sys$co, control = list(errx = 1e-06, 
    maxit = 50, trace = 1, ci = list(report = T), history = F, 
    adaptbt = T), e = NULL, eco = NULL, flsi = lsi_ln, sys$data_meas, 
    sys, sim_fun) at physio_fit.R#502
1.
physio_fit(datfile = "example.txt")
```

**Comment by bdelepine** [comment]
I noticed that the version of `nlsic.R` is behind the one used in influx. I replaced this file and sourced `tools_ssg.R` too since it is now somehow needed by `nlsic.R`... and it fixed it for me, i.e. no more traceback.

**Comment by pierremillard** [comment]
Hello @bdelepine ,

thanks for your feedback and the solution!

I have updated nlsic (and added tools_ssg) as you suggested. I have also changed the lower bound constraint on growth rate from 0 to 1e-6 to ensure numerical stability in some situations.

Please, could you check that the dev branch works correctly with your data?

**Comment by bdelepine** [comment]
I tested the dev branch and it worked out-of-the-box. Thanks!
